### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by firehist** [rawmind0/rancher-traefik#3]
I wondering if you have any advise about how include SSL configuration?
Is it correct to add a configuration block in toml (https://github.com/containous/traefik/issues/376)

**Comment by rawmind0** [comment]
Traefik already implements ssl layer and SNI, but it is not yet implemented in the rancher-traefik integration. 

I'm already working on this topic, to be able to specify ssl config and to provide ssl keys/certs at deployment time. I expected that it could be finished very soon. :)

**Comment by rawmind0** [comment]
I made a first ssl integration in traefik. By the moment it uses a default example key/crt and you could overwrite them i rancher catalog form.

I'm working to get certificates though rancher-api and make able sni configurations.

**Comment by rawmind0** [comment]
https://github.com/rancher/community-catalog/pull/185

**Comment by firehist** [comment]
Hey :) Thanks for the job!
I worked a little on my side too. The idea to set `traefik(crt|key)` is cool to manage only one certificate, but I wondering how manage multiple domain depending on the request.
I added on my side (privatly cause did in a very very very ugly way 💩 ) a new way to declare domain without any magical naming:
- `traefik.enable = direct`
- `traefik.domain = my.domain.com`
- `traefik.port = 8080`

It will expose this DNS directly without stack or service names relation.

I also set multiple certificates in traefik.toml file:

```
@defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/traefik/certs/domain.io.cert"
        KeyFile = "/etc/traefik/certs/domain.io.key"
      [[entryPoints.https.tls.certificates]]
        CertFile = "/etc/traefik/certs/domain.tv.cert"
        KeyFile = "/etc/traefik/certs/domain.tv.key"
```

So my suggestion should be:
1. Think about a direct way to declare Domain name
2. Think about a flexible way to add certificates (maybe an env variable with path to `domain.tld.(key|cert)` files

What do you think about?

**Comment by rawmind0** [comment]
Hi @firehist. Thanks so much for the feedback.

The 2 points that you propose are interesting, but they have some nuances.
- Direct way to declare Domain name: This feature could seem very good, but it has problems. What happens if two different services set the same domain name?? As traefik package was thought as a global package, you have to assure that the names are unique, to avoid conflicts. This is why, conf add stack_name or service_name.stack_name, to assure that the names are unique. In this point, i added the feat of define multiple values in traefik_domain, separated by ','. With this you are able to publish in different domains.
- flexible way to add certificates: This would be pretty cool. In fact, the feature is already added to alpine-traefik. You could add a path with different key/crt files and they are all configured automatically, and enabled sni. Please look at the "ssl configuration" at README.md of alpine-traefik. https://hub.docker.com/r/rawmind/alpine-traefik/
  The problem here, is the integration with rancher. I'm working to integrate de catalog package with ranchers certificates, and the possibility to add more than one. The issue is that i'm able to get cert's, through the rancher api,  but not key's. 

Best regards....
