### ISSUE TITLE
:8080 404 page not found and empty Providers

### ISSUE THREAD

**Issue by jujes** [rawmind0/rancher-traefik#32]
Hi, after setup the service and add Infrastructure > Hosts
someone can tell me how fix it?

**traefik_lb=True**
I get an 404 page into main rancher page and empty Providers in traefik main page :8000
attach captures:
![issue_01](https://cloud.githubusercontent.com/assets/2881017/22854350/e7f710de-f06c-11e6-9ab9-73fe5e678f91.png)
![issue_02](https://cloud.githubusercontent.com/assets/2881017/22854351/e7fc1d7c-f06c-11e6-8dd7-11da81f741ee.png)
thanks in advance,

**Comment by rawmind0** [comment]
Hi @jujes ...

How are you running traefik?? In which ports is it listening?? Is it running at the same host as rancher-server?? 

What do you mean with main rancher page?? 
* If you mean that you are trying to access rancher-server:8080 and you get a 404 page not found, could be that you are running traefik and the same host:port that rancher-server. If so, remove traefik label from the host that is running rancher-server, remove traefik docker from it and restart rancher-server.

* If you mean that you are trying to access any service through traefik expose port, could be because you don't have any service published. Please, review your service traefik labels.

Do you have any service with the correct traefik labels added and health check working?? Empty traefik admin page:8000 would be empty if there isn't any service to publish.

**Comment by jujes** [comment]
Hi @rawmind0 
Yes, I'm running both in the same saver...
how I can deploy in the same server rancher and traefik?

here a short video about my issue:

[![issue traefik-rancher ](https://i9.ytimg.com/vi/GL0Hn1ejvUg/2.jpg?sqp=CJDR_cQF&rs=AOn4CLA7_Q4VQaCWqlVw4W0usOqYcoe4mw&time=1486842142928)](https://www.youtube.com/watch?v=GL0Hn1ejvUg)

thanks in advance,

**Comment by rawmind0** [comment]
Hi @jujes ... the video is unavailable....

If you are running on the same server, simply change the port where traefik listen..something different from the 8080 that is already used by rancher-server...

**Comment by jujes** [comment]
Hi @rawmind0 I forget make public the video, now is available 
https://youtu.be/GL0Hn1ejvUg

**Comment by rawmind0** [comment]
Please, read the previos response...
