### ISSUE TITLE
Rancher-Traefik catalog to hookup Traefic to Marathon.

### ISSUE THREAD

**Issue by pvcon13** [rawmind0/rancher-traefik#36]
Hello again Raul.
I read this closed issue:  https://github.com/rawmind0/rancher-traefik/issues/17

Question. I would like to run this on every host in Rancher so that Traefik knows how to contact all instances of Marathon (known by Rancher as it creates those hosts and starts the marathon containers).

The goal is to use Traefik to use that Rancher DNS to locate Marathon to extract and monitor containers launched by Marathon using the standard marathon monitoring setup in Traefik.

I can't (seem to) run rancher-traefik catalog in Rancher under the mesos cluster (my default system). Can I? How? 

I would assume that to track which hosts Marathon is running on (to be able to interact with a changing group of marathon containers on differing hosts), I would not benefit from running Traefik on a cattle group, or would I?

What would you suggest, Raul?

I would think Rancher DNS or Rancher Metadata would know where marathon is and that would be configured into the setup for traefik? Yes/No/Other?  :)

Thanks as always

**Comment by rawmind0** [comment]
Hi @pvcon13 

To run traefik in mesos/marathon environments, you don't need this package. This is only for cattle environments, soon not needed due to traefik integration with cattle, https://github.com/containous/traefik/pull/1173

Traefik has a built in mesos/marathon integration, you only need to launch the official traefik container, with the correct config for marathon or mesos, https://docs.traefik.io/toml/#marathon-backend https://docs.traefik.io/toml/#mesos-generic-backend
Then, in your services, add the correct labels to add them to traefik config.

Best regards...

**Comment by pvcon13** [comment]
ok, sounds great.

I was concerned that Marathon's IP would change, and that only Rancher would know the new IP address of Marathon. 

I had assumed that I would have to add a DNS Name to the Traefic configurations to track marathon's IP address.
