### ISSUE TITLE
Define full domain name in racher label(s)

### ISSUE THREAD

**Issue by dirkdevriendt** [rawmind0/rancher-traefik#4]
Nice work!
Feature request: It would seem useful to be able to override "service.stack.domain.com" with a completely arbitrary domain name?

**Comment by rawmind0** [comment]
@dirkdevriendt - thanks so much about your feedback.... :)

There is a pull request with this feature, https://github.com/rawmind0/rancher-traefik/pull/2, but i'm not sure if it is the way.

It seems a good feature to be able to override "service.stack.domain.com" with a completely arbitrary domain name. It would be so easy to do, but it could be problematic. What happens if two different services define the same value for traefik.host?? 

At initial version, i scoped the traefik service in that way, but i changed it to assure that the frontend and its rules are unique. I think it's a must, due to it may have conflicts and compromise the access to some services if you repeat a value of traefik.host in some service, from the same or from another stack. By the moment, i don't know an easy way to assure it. 

Automatic name could be one of two, myservice.mystack.mydomain if service label traefik.enable=true or mystack.mydomain if service label traefik.enable=stack (and you only publish a service from that stack).
What do you think to have a label for public and private domain and publish both??
The automatic names could be myservice.mystack.myprivatedomain and myservice.mystack.mypublicdomain or mystack.myprivatedomain and mystack.mypublicdomain.

**Comment by dirkdevriendt** [comment]
Indeed, I understood the reasoning and was wondering if I should mention the possible domain config clashes, but as expected, you're already two steps ahead of me...

Thanks for the pointer to the PR, I'll take the discussion there.

Note: don't thank me, I'm very impressed and becoming a bigger rancher fan every day :-)

**Comment by rawmind0** [comment]
Issue closed due to PR https://github.com/rawmind0/rancher-traefik/pull/2 ...
