### ISSUE TITLE
upstream integration

### ISSUE THREAD

**Issue by joshuacox** [rawmind0/rancher-traefik#40]
In this [issue](https://github.com/rawmind0/rancher-traefik/issues/36) you indicate this project will become obsolete.   Can we get some discussion on upgrade path?  Will there be a new rancher catalog template?  Or is there some other way we should be spawning traefik etc?

**Comment by rawmind0** [comment]
Hi @joshuacox ...

Once i have time to update the catalog package with the new version of traefik, that has built in rancher support, i guess that rancher-traefik would be deprecated. 

I'm not pretty sure yet, how to upgrade, due to i have to take time to test. Once i have a clear idea, i comment on this issue. Any suggestion would be appreciated. :)

**Comment by joshuacox** [comment]
As for upgrades, so long as there is still a traefik item in the community catalog I'm happy.  If I have had any issues so far I had just deleted the whole thing and started over.

@kelchm seems to imply [here](https://github.com/containous/traefik/issues/1326) that we should not be using this project at all.  But I am unaware of another project that provides a traefik catalog item for rancher at the moment.

I can certainly write my own templates and every now and then I'll even fire off a stack without caring about reproducibility.  But I'd much rather have a well thought out and maintained method.  So I surely appreciate the work you've done here.

**Comment by tboyce021** [comment]
I'd still be interested in this. I need some fixes from v1.2.0, so I tried setting it up myself with the official Traefik image + Rancher integration but ran into bugs with it. Will this project get updated to use a later version of Traefik, and if so will it start using the built-in Rancher instead of the current templates? Should I just start using the offical Traefik image or this project?

Also, is there a quick way to update this to use the latest version of Traefik but keep using the current template system? That would probably take care of both of my issues, but I didn't see how to do that even if I fork the project.

Edit: Never mind. I see now the Traefik container actually uses [alpine-traefik](https://github.com/rawmind0/alpine-traefik) and there are newer images available for that. It's still unclear whether I should continue to use this project, or just set up Traefik + Rancher myself from the offical image.

**Comment by tboyce021** [comment]
Nevermind, I see now the Traefik container actually uses [alpine-traefik](https://github.com/rawmind0/alpine-traefik) and there are newer images available for that.

**Comment by kelchm** [comment]
@tboyce021, My recommendation would be to switch to the official rancher integration once v1.3 of Traefik is released.

**Comment by rawmind0** [comment]
Updated alpine-traefik to last 1.2.3 version....
https://github.com/rawmind0/alpine-traefik/pull/30

**Comment by joshuacox** [comment]
@rawmind0  do you have a template somewhere where we can test this?  perhaps a new branch could  be made here: https://github.com/rawmind0/service-catalog

**Comment by rawmind0** [comment]
Sure...Published at service-catalog repo..

https://github.com/rawmind0/service-catalog

**Comment by joshuacox** [comment]
@rawmind0 works great, although, mine never came out of the 'initializing' yellow state.   Funny thing is, looking at the healthcheck and seeing as how it is only looking at port 8000, I can't figure out why as port 8000 works just fine (I'm looking at the dashboard now).
