### ISSUE TITLE
Config file generation error

### ISSUE THREAD

**Issue by marcbachmann** [rawmind0/rancher-traefik#7]
I can't get the container to run. I'm using the template from https://github.com/rawmind0/service-catalog/tree/master/templates/traefik/1

If found that error log in the `/opt/tools/confd/log/confd.log` file:

```
2016-07-25T09:32:26Z traefik-traefik_1 /opt/tools/confd/bin/confd[11]: ERROR template: rules.toml.tmpl:26:93: executing "rules.toml.tmpl" at <getv (printf  "/stack...>: error calling getv: key does not exist
```

Any idea how to fix it?

It would be nice if the config container would crash when there's an error. That wasn't the case. I wasn't able to see any log in there. Maybe that's something that rancher can improve.

**Comment by rawmind0** [comment]
Hi @marcbachmann,

it seems that you doesn't set traefik.domain label to your services. It tries to get value of that label at rules.toml.tmpl:26:93. 

Setting traefik.domain label to the services where you already add traefik.enable label, would solve the problem. As you could see at "configuration labels" section ,traefik.enable, traefik.domain and traefik.port labels are mandatory in services.

You could find logs of all components at traefik container,
- monit logs: /opt/monit/log
- traefik logs: /opt/traefik/log
- confd logs: /opt/tools/confd/log

Best regards...

**Comment by marcbachmann** [comment]
Oh. that logging could be better. You're right. I had a service that didn't have that config.
I had to check the `/services` endpoint to find the service.

**Comment by marcbachmann** [comment]
One question to the domains. Why do you hardcode the domain to `service.stack.domain`?
Isn't it much easier/more flexible to just use the domain without service & stack prefixes?
interpolation is much more flexible `$${stack_name}.$${service_name}.example.com`.
And there's less magic and easier to understand.

**Comment by rawmind0** [comment]
I'm sorry @marcbachmann , i don't understand very well your question...
Do i hardcode the domain to service.stack.domain?? These values are looked at metadata service, and generated dynamically. They form the URL where the service is available.

It's pretty sure that it would be easy just to use the domain, but you must assure that generated names are unique. That's why i add service & stack, because they assure that the names are unique. 

I could agree with you that $${service_name}.$${stack_name}.domain could be easy to understand, but more flexible?? It would be almost the same, the only difference is the source to get the values....I think that i don't understand very well your point..:P
