### ISSUE TITLE
Error calling getv

### ISSUE THREAD

**Issue by firehist** [rawmind0/rancher-traefik#8]
Hello @rawmind0 
How are you?
I get stuck on this error `2016-07-26T13:33:02Z traefik_traefik_1 /opt/tools/confd/bin/confd[17]: ERROR template: rules.toml.tmpl:16:146: executing "rules.toml.tmpl" at <getv (printf "/stack...>: error calling getv: key does not exist: /stacks/hello-world/services/hello-world/containers/stacks/health_state`.

Run latest version of `rancher-traefik` and `alpine-traefik`. Everything is working fine but the healthCheck doesn't.

I run a `tutum/hello-world` with an health check on port 80 (it works) and traefik labels.

Do you have an idea to how debug that?

Thanks a lot.
Ben.

**Comment by rawmind0** [comment]
Hi @firehist,

how are you doing?? :)

How did you run your container?? Is your container called "stacks"??
I try to reproduce your error, but in my system is working well. I've created and stack called hello-world, with a service called hello-world and traefik labels and it's working ok, no errors at all and the service is configured in the traefik.....These are the docker-compose and the rancher-compose.....

![image](https://cloud.githubusercontent.com/assets/11555446/17140711/b9015962-5349-11e6-902f-0ee0446fce73.png)

![image](https://cloud.githubusercontent.com/assets/11555446/17140759/e79766e0-5349-11e6-954b-a86a29bc26f0.png)

What version of the traefik package are you using?? In this repo, https://github.com/rawmind0/service-catalog , there are the latest catalog packages version...

Please, review your hello-world deployment, because it's an strange error....

Best regards...

**Comment by firehist** [comment]
Thanks a lot for the quick response !

Mmmh, I try both and same error.
I forgot to say that I have set-up two environments: tools & prod. Traefik works well on `tools` but on `prod`Aie!
I'm not able to `ping rancher-metadata` from the traefik container so I thinks that something is broken with rancher!

**Comment by rawmind0** [comment]
Take into account that it is a traefik integration with rancher. You need that your containers would be able to ping rancher-metadata, in order to the integration works. The getv error that you attached before, may be because of this.

Please, review that point...:)

**Comment by firehist** [comment]
Yes, I totally agree. It's definitely a rancher bug, I'll try to google it but until now nothing new 👯 
Sorry for the issue, and thank you for the response!

**Comment by jjscarafia** [comment]
@firehist have you been able to solve this? I'm facing a similar issue that I've posted here https://github.com/rawmind0/rancher-traefik/issues/42#issuecomment-308426852

I appreciate any information.
Thanks!

**Comment by firehist** [comment]
Hello @jjscarafia 
If I well remember, using a new version from the catalog help to make this bug disappear.
Since that we moved onto a full K8s stack and so we no longer use traefik and not a lot rancher.

Sorry to not help you so much!

An other point, I was facing troubles with internal rancher networking services. Solution is to restart networking services (when a problem of ping appears).

Good luck!

**Comment by jjscarafia** [comment]
Thanks @firehist for the feedback!
No luck for now :) but will keep trying...
